name: google_calendar
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  intl: ^0.19.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans/OpenSans-Regular.ttf
        - asset: assets/fonts/opensans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/opensans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/opensans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/opensans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/opensans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/opensans/OpenSans-ExtraBold.ttf
          weight: 800
